config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :friends, only: :index do
    member do
      post :follow
    end
  end

  resource  :account
  resources :authorizations, only: [:destroy]

  root to: 'home#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Find your Twitter friends on Mastodon - Mastodon Bridge

    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

    %meta{ property: 'og:type', content: 'article' }/
    %meta{ property: 'og:title', content: 'Find your Twitter friends on Mastodon' }/
    %meta{ property: 'og:description', content: 'This bridge tool matches you with your friends in the decentralized Mastodon network' }/
    %meta{ property: 'og:image', content: image_url('preview.jpg') }/
    %meta{ property: 'og:url', content: root_url }/
    %meta{ property: 'og:site_name', content: 'Mastodon Bridge' }/

    %meta{ name: 'twitter:card', content: 'summary' }/
    %meta{ name: 'twitter:site', content: '@MastodonProject' }/
  %body
    .header
      %ul.left
        %li
          = link_to root_path, class: 'brand' do
            = image_tag 'logo_full.svg', alt: 'Mastodon Bridge'

      %ul.right
        - if twitter?
          %li= link_to 'Friends', friends_path

        - if user_signed_in?
          %li= link_to 'Account', account_path
          %li= link_to 'Logout', destroy_user_session_path, method: :delete

    - if flash[:notice]
      .flash-message
        %strong Success!
        = flash[:notice]
    - if flash[:alert]
      .flash-message
        %strong Oops!
        = flash[:alert]

    = yield

    %hr/

    %p.footer
      This website is run by
      %a{:href => "https://mastodon.social/@Mastodon"} @Mastodon@mastodon.social
      \/
      = succeed "." do
        %a{:href => "https://twitter.com/MastodonProject"} @MastodonProject
      %a{:href => "https://github.com/tootsuite/mastodon-bridge", :target => "_blank"} Source code